#include "sprites.h"

#include "assets_sprites.h" // generated by nob.c

#include <string.h>

void sprites_load(Sprites *s, Mach_Renderer *r) {
    s->count = 0;
    s->r = r;
    for (i32 i = 0; i < (i32)EMBEDDED_SPRITE_COUNT && i < MAX_SPRITES; i++) {
        const Embedded_Sprite *e = &EMBEDDED_SPRITES[i];

        // Nearest filtering: pixel art, drawn at integer-ish zoom. Linear blurs it.
        Mach_R2D_Texture tex = mach_r2d_texture_from_memory(r, e->data, e->size, MACH_TRUE);
        if (!tex.id) {
            MACH_LOG_ERROR("sprite '%s' failed to decode (%d bytes)", e->name, e->size);
            continue;
        }
        s->items[s->count].name = e->name;
        s->items[s->count].tex = tex;
        s->count++;
    }
    if (s->count > 0)
        MACH_LOG_INFO("loaded %d embedded sprite(s)", s->count);
}

void sprites_unload(Sprites *s) {
    if (!s->r)
        return;
    for (i32 i = 0; i < s->count; i++)
        mach_r2d_destroy_texture(s->r, &s->items[i].tex);
    s->count = 0;
    s->r = NULL;
}

Mach_R2D_Texture sprites_get(const Sprites *s, const char *name) {
    for (i32 i = 0; i < s->count; i++) {
        if (strcmp(s->items[i].name, name) == 0)
            return s->items[i].tex;
    }
    return (Mach_R2D_Texture){0};
}
