#!/usr/bin/env bash
# Compile-check the engine + game declarations against the names X11 and Win32
# inject into the implementation TU (RGFW includes Xlib.h / windows.h there).
#
# The OS names are faked so the check runs on any dev box: a collision like the
# old `Font` type vs X11's `typedef XID Font` fails here without needing a
# Linux machine. Faking them *before* mach.h is deliberately worse than the
# real include order — anything that passes here survives the real headers.
#
# Usage: scripts/check_namespace.sh   (from anywhere; exits nonzero on collision)

set -euo pipefail
cd "$(dirname "$0")/.."

cc="${CC:-clang}"
stub="build/.namespace_stub.c"
mkdir -p build

cat > "$stub" <<'EOF'
// Generated by scripts/check_namespace.sh. Fake OS-header names, then compile
// the engine and game declarations against them.

// X11 (<X11/X.h>, <X11/Xlib.h>)
typedef unsigned long XID;
typedef XID Font;
typedef XID Window;
typedef XID Cursor;
typedef XID Pixmap;
typedef XID Colormap;
typedef XID Drawable;
typedef XID KeySym;
typedef unsigned long Atom;
typedef unsigned long Time;
typedef struct _XDisplay Display;
typedef struct _XScreen Screen;
typedef struct _XVisual Visual;
typedef struct _XDepth Depth;
typedef struct _XRegion *Region;
typedef struct _XGC *GC;
#define Bool int
#define Status int
#define True 1
#define False 0
#define None 0L
#define Success 0
#define Above 0
#define Below 1
#define Complex 0
#define Nonconvex 1
#define Convex 2
#define Expose 12
#define KeyPress 2
#define ButtonPress 4
#define ParentRelative 1L
#define CopyFromParent 0L
#define CurrentTime 0L

// Win32 (<windows.h>): the empty near/far keyword macros and GDI functions
// whose names would clash with same-named types or functions of ours.
#define near
#define far
int Rectangle(void *hdc, int l, int t, int r, int b);
int Polygon(void *hdc, const void *pts, int n);
int Ellipse(void *hdc, int l, int t, int r, int b);

#include "mach.h"
#include "game/game.h"
#include "game/render_game.h"

int main(void) { return 0; }
EOF

"$cc" -std=c99 -Wall -Wextra -fsyntax-only \
  -I. -Isrc -Ithird_party/rgfw -Ithird_party/stb -Ithird_party/clay \
  "$stub"

echo "namespace check OK: engine/game names don't collide with X11/Win32"
