#!/usr/bin/env bash
# Offline shader compiler. Authors live once in HLSL (src/engine/render/shaders);
# this cross-compiles each to every SDL_GPU bytecode format and bakes the results
# into a generated C header so the unity build stays a single self-contained
# binary (no runtime shader files).
#
# Pipeline:
#   HLSL --glslangValidator--> SPIR-V        (Vulkan: Linux + Windows)
#   SPIR-V --spirv-cross----->  MSL          (Metal: macOS)
#   DXIL/D3D12 is deferred (needs DXC); Windows runs on Vulkan for now.
#
# Tooling (Homebrew: `brew install glslang spirv-cross`; apt: glslang-tools
# spirv-cross). Re-run after editing any .hlsl, then rebuild. The generated
# header is committed so a plain `./build.sh` needs no shader toolchain.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

src_dir="src/engine/render/shaders"
out_header="src/engine/render/shaders_generated.h"

for tool in glslangValidator spirv-cross; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: '$tool' not found. Install glslang + spirv-cross." >&2
    exit 1
  fi
done

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Emit one C byte array for a binary blob: emit_array <c_name> <file>
emit_array() {
  local name="$1" file="$2"
  printf 'static const unsigned char %s[] = {\n' "$name"
  od -An -v -tu1 "$file" | awk '
    { for (i = 1; i <= NF; i++) { printf "%s,", $i; if (++n % 16 == 0) printf "\n" } }
    END { if (n % 16) printf "\n" }'
  printf '};\n'
  printf 'static const unsigned long %s_len = sizeof(%s);\n\n' "$name" "$name"
}

{
  printf '// Auto-generated by scripts/shaders.sh / shaders.ps1 -- do not edit.\n'
  printf '// Authored HLSL lives in src/engine/render/shaders/*.hlsl.\n'
  printf '#ifndef SHADERS_GENERATED_H\n#define SHADERS_GENERATED_H\n\n'
} > "$out_header"

for hlsl in "$src_dir"/*.hlsl; do
  base="$(basename "$hlsl" .hlsl)"          # e.g. lit.vert
  case "$base" in
    *.vert) stage=vert ;;
    *.frag) stage=frag ;;
    *) echo "error: cannot infer stage from '$base' (need .vert/.frag)" >&2; exit 1 ;;
  esac
  cname="${base//./_}"                        # e.g. lit_vert

  spv="$work/$cname.spv"
  msl="$work/$cname.metal"

  echo "compiling $hlsl"
  # HLSL -> SPIR-V. glslang honors register(bN, spaceM) -> descriptor set M.
  glslangValidator -V -D -S "$stage" -e main --source-entrypoint main \
    "$hlsl" -o "$spv" >/dev/null

  # SPIR-V -> MSL. --msl-decoration-binding makes MSL resource indices follow
  # the SPIR-V binding decoration, which is what SDL_GPU's Metal backend expects
  # (uniform slot i -> buffer(i), texture/sampler i -> texture(i)/sampler(i)).
  spirv-cross --msl --msl-decoration-binding "$spv" --output "$msl"

  emit_array "shader_${cname}_spv" "$spv" >> "$out_header"
  emit_array "shader_${cname}_msl" "$msl" >> "$out_header"
done

printf '#endif // SHADERS_GENERATED_H\n' >> "$out_header"
echo "wrote $out_header"
