# Offline shader compiler (Windows parity of scripts/shaders.sh).
#
# Authors live once in HLSL (src/engine/render/shaders); this cross-compiles
# each to SPIR-V (Vulkan: Windows/Linux) and MSL (Metal: macOS) and bakes them
# into the committed shaders_generated.h, so the unity build stays a single
# self-contained binary with no runtime shader files.
#
# Tooling: glslangValidator + spirv-cross, both of which ship with the LunarG
# Vulkan SDK (https://vulkan.lunarg.com). Install it and reopen the prompt so
# they are on PATH. Only needed when editing a .hlsl -- the committed header
# lets build.bat run without any shader toolchain.
#
# DXIL/D3D12 is deferred (needs DXC); Windows runs on the Vulkan backend, which
# gpu.c selects automatically by requesting only SPIR-V/MSL formats.

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$srcDir = "src\engine\render\shaders"
$outHeader = "src\engine\render\shaders_generated.h"

foreach ($tool in @("glslangValidator", "spirv-cross")) {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        Write-Error "'$tool' not found. Install the LunarG Vulkan SDK and reopen the prompt."
    }
}

$work = New-Item -ItemType Directory -Force `
    -Path (Join-Path $env:TEMP ("mach_shaders_" + [guid]::NewGuid()))

# Use LF newlines explicitly so the generated header is byte-compatible with the
# bash generator (no CRLF churn when regenerated on Windows).
$nl = "`n"

# Emit one C byte array for a binary blob.
function Emit-Array($name, $file) {
    $bytes = [System.IO.File]::ReadAllBytes($file)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.Append("static const unsigned char $name[] = {$nl")
    for ($i = 0; $i -lt $bytes.Length; $i++) {
        [void]$sb.Append("$($bytes[$i]),")
        if ((($i + 1) % 16) -eq 0) { [void]$sb.Append($nl) }
    }
    if (($bytes.Length % 16) -ne 0) { [void]$sb.Append($nl) }
    [void]$sb.Append("};$nl")
    [void]$sb.Append("static const unsigned long ${name}_len = sizeof($name);$nl$nl")
    return $sb.ToString()
}

$out = [System.Text.StringBuilder]::new()
[void]$out.Append("// Auto-generated by scripts/shaders.sh / shaders.ps1 -- do not edit.$nl")
[void]$out.Append("// Authored HLSL lives in src/engine/render/shaders/*.hlsl.$nl")
[void]$out.Append("#ifndef SHADERS_GENERATED_H$nl#define SHADERS_GENERATED_H$nl$nl")

Get-ChildItem (Join-Path $srcDir "*.hlsl") | Sort-Object Name | ForEach-Object {
    $hlsl = $_.FullName
    $base = $_.BaseName                       # e.g. lit.vert
    switch -Wildcard ($base) {
        "*.vert" { $stage = "vert" }
        "*.frag" { $stage = "frag" }
        default  { Write-Error "cannot infer stage from '$base' (need .vert/.frag)" }
    }
    $cname = $base -replace '\.', '_'          # e.g. lit_vert
    $spv = Join-Path $work "$cname.spv"
    $msl = Join-Path $work "$cname.metal"

    Write-Host "compiling $hlsl"
    # HLSL -> SPIR-V. glslang honors register(bN, spaceM) -> descriptor set M.
    & glslangValidator -V -D -S $stage -e main --source-entrypoint main $hlsl -o $spv | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Error "glslangValidator failed for $hlsl" }

    # SPIR-V -> MSL. --msl-decoration-binding makes MSL resource indices follow
    # the SPIR-V binding decoration, matching SDL_GPU's Metal backend.
    & spirv-cross --msl --msl-decoration-binding $spv --output $msl
    if ($LASTEXITCODE -ne 0) { Write-Error "spirv-cross failed for $cname" }

    [void]$out.Append((Emit-Array "shader_${cname}_spv" $spv))
    [void]$out.Append((Emit-Array "shader_${cname}_msl" $msl))
}

[void]$out.Append("#endif // SHADERS_GENERATED_H$nl")

# Write without a BOM and with the LF newlines assembled above.
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText((Join-Path $repoRoot $outHeader), $out.ToString(), $utf8NoBom)

Remove-Item -Recurse -Force $work
Write-Host "wrote $outHeader" -ForegroundColor Green
